services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: shopping-list-api-app
    container_name: shopping-list-api-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "9000:9000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:XeehsAfFdfnl9GG/Aq8SKv+QkIsRqid6oxuzqTH61t4=
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=shopping_list
      - DB_USERNAME=shopping_user
      - DB_PASSWORD=shopping_pass
    depends_on:
      - db

  nginx:
    image: nginx:1.25
    container_name: shopping-list-api-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mariadb:11.0
    container_name: shopping-list-api-db
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: shopping_list
      MARIADB_USER: shopping_user
      MARIADB_PASSWORD: shopping_pass
      MARIADB_ROOT_PASSWORD: root_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
